max_speed_linear: 0.1
max_speed_angular: 0.4

manipulator_command_topic: /manipulator_arm_control/twist_cmd

controller_manager_switch_service: /manipulator_arm_control/controller_manager/switch_controller
standard_controllers:
  - manipulator_arm_traj_controller
  - gripper_traj_controller
teleop_controllers:
  - arm_joystick_control