max_linear_speed: 1.0
max_angular_speed: 2.0

slow_factor: 0.2
normal_factor: 0.4
fast_factor: 0.6

#critical_stability_lower_threshold: 0.5
#critical_stability_upper_threshold: 0.7
#stability_margin_topic: /stability_visualization/stability_margin

response_curve: "parabola"

drive_command_topic: "cmd_vel"
