# for unknown mappings joystick axes or button to array index: "sudo jstest /dev/input/jsX" (X is mostly 0) and then test each axes/button on gamepad

# order needs to be same as in joy message!

# WARNING: when using LT/RT the code probably needs to be adapted, since LT/RT axes are from [-1.0,1.0] with 1.0 as default value!

axes:
  - steer            # 0: left joystick: left/right
  - speed            # 1: left joystick: up/down
  - ""               # 2: LT
  - ""               # 3: right joystick: left/right
  - ""               # 4: right joystick: up/down
  - ""               # 5: RT
  - ""               # 6: cross: left/right
  - ""               # 7: cross: up/down


buttons:
  - ""           # 0: A
  - very_slow    # 1: B
  - ""           # 2: X
  - slow         # 3: Y
  - ""           # 4: LB
  - ""           # 5: RB
  - ""           # 6: back
  - ""           # 7: start
  - ""           # 8: logitech
  - ""           # 9: left joystick press
  - ""           # 10:right joystick press