max_linear_speed: 1.0
max_angular_speed: 1.5

slow_factor: 0.4
normal_factor: 0.6
fast_factor: 1

#critical_stability_lower_threshold: 0.5
#critical_stability_upper_threshold: 0.7
#stability_margin_topic: /stability_visualization/stability_margin

response_curve: "parabola"

drive_command_topic: "cmd_vel"
wb_assistance_enable_topic: "/whole_body_posture_assistance/enable"
