# for unknown mappings of [joystick axes or buttons] to [array index]: "sudo jstest /dev/input/jsX" (X is often 0) and then test each axis/button on gamepad

# order needs to be same as in joy message!

# WARNING: when using LT/RT the code probably needs to be adapted, since LT/RT axes are from [-1.0,1.0] with 1.0 as default value
#  (or use mapTriggerAxes(msg) to map it to [0,1] with 0.0 as default)

# NOTES:
# 1. In oder to split an axis into two partial axes or buttons write the two names seperated with a semicolon (and no spaces!).
#     The first one belongs to the part < 0, the second one to the part > 0 (e.g. "<nameA>_inc;<nameB>_inc")
# 2. In order to combine two (partial) axes or buttons into one axis use the suffixes <name>_inc and <name>_dec (e.g. front_inc and front_dec)
#
# WARNING: For all axes (except the trigger) are the maximal values: left: +1.0, right: -1.0, up: +1.0, down: -1.0
# Hence, when splitting a left/right axis, the first value is on the RIGHT part, the second on the LEFT part of axis.

axes:
  - ""  # 0: left joystick: right/left
  - ""  # 1: left joystick: down/up
  - "pan"  # 2: right joystick: right/left
  - "tilt"  # 3: right joystick: down/up
  - ""  # 4: RT
  - ""  # 5: LT
  - ""  # 6: cross: right/left
  - ""  # 7: cross: down/up


buttons:
  - ""  # 0: A
  - ""  # 1: B
  - ""  # 2:
  - ""  # 3: X
  - ""  # 4: Y
  - ""  # 5:
  - ""  # 6: LB
  - ""  # 7: RB
  - ""  # 8:
  - ""  # 9:
  - ""  # 10: back
  - ""  # 11: start
  - ""  # 12: 
  - ""  # 13: left joystick press
  - "reset"  # 14:right joystick press
