speed: 0.5

flipper_front_command_topic: /telemax_control/flipper_front_velocity/command 
flipper_back_command_topic: /telemax_control/flipper_back_velocity/command

controller_manager_switch_service: /telemax_control/controller_manager/switch_controller
controller_manager_list_service: /telemax_control/controller_manager/list_controllers

standard_controllers: 
  - flipper_traj_controller
teleop_controllers: 
  - flipper_front_left_velocity_controller 
  - flipper_front_right_velocity_controller 
  - flipper_back_left_velocity_controller 
  - flipper_back_right_velocity_controller

num_tries_switch_controller: 5
sleep_between_tries_sec: 1

flipper_front_factor: -1.0